//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonus()
        {
            this.Bonus_Records = new HashSet<Bonus_Records>();
        }
    
        public int Bonus_Id { get; set; }
        public string BonusName { get; set; }
        public decimal Bonus_pirce { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Bonus Bonus1 { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Bonus Bonus2 { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonus_Records> Bonus_Records { get; set; }
    }
}
