//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cwa_Rd_View
    {
        public int CR_id { get; set; }
        public int Staff_id { get; set; }
        public string Staff_Name { get; set; }
        public string Cwa_Name { get; set; }
        public decimal CR_Frequency { get; set; }
        public System.DateTime CR_date { get; set; }
        public string Store_Name { get; set; }
    }
}
