//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagemanagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WagemanagementEntities : DbContext
    {
        public WagemanagementEntities()
            : base("name=WagemanagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bonus> Bonus { get; set; }
        public virtual DbSet<Bonus_Records> Bonus_Records { get; set; }
        public virtual DbSet<Cwa> Cwa { get; set; }
        public virtual DbSet<Cwa_Records> Cwa_Records { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Subsidy> Subsidy { get; set; }
        public virtual DbSet<Subsidy_Records> Subsidy_Records { get; set; }
        public virtual DbSet<Wages_Records> Wages_Records { get; set; }
        public virtual DbSet<Bonus_Rd_View> Bonus_Rd_View { get; set; }
        public virtual DbSet<Cwa_Rd_View> Cwa_Rd_View { get; set; }
        public virtual DbSet<Staff_View> Staff_View { get; set; }
        public virtual DbSet<Subsidy_View> Subsidy_View { get; set; }
        public virtual DbSet<Wages_View> Wages_View { get; set; }
    }
}
