//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Bonus_Records = new HashSet<Bonus_Records>();
            this.Cwa_Records = new HashSet<Cwa_Records>();
            this.Subsidy_Records = new HashSet<Subsidy_Records>();
            this.Wages_Records = new HashSet<Wages_Records>();
        }
    
        public int Staff_id { get; set; }
        public string Staff_Pwd { get; set; }
        public string Staff_Name { get; set; }
        public string Sraff_State { get; set; }
        public int Role_id { get; set; }
        public int Grade_Id { get; set; }
        public int Department_Id { get; set; }
        public int Staff_Sex { get; set; }
        public string Staff_Address { get; set; }
        public string Staff_Phone { get; set; }
        public int Store_Id { get; set; }
        public string Staff_Email { get; set; }
        public Nullable<System.DateTime> Staff_hiredate { get; set; }
        public string Staff_Remark { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonus_Records> Bonus_Records { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cwa_Records> Cwa_Records { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Department Department { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Grade Grade { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Role Role { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        public virtual Store Store { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subsidy_Records> Subsidy_Records { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wages_Records> Wages_Records { get; set; }
    }
}
