//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wagemanagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_View
    {
        public int Staff_id { get; set; }
        public string Staff_Name { get; set; }
        public string GradeName { get; set; }
        public string Role_Name { get; set; }
        public string Dt_Name { get; set; }
        public string Store_Name { get; set; }
        public string Staff_Address { get; set; }
        public string Staff_Phone { get; set; }
        public string Sraff_State { get; set; }
        public int Staff_Sex { get; set; }
        public string Staff_Email { get; set; }
        public Nullable<System.DateTime> Staff_hiredate { get; set; }
        public string Staff_Remark { get; set; }
    }
}
